allowBuilds:
  esbuild: true
  '@shimpz/frontend@https://codeload.github.com/TheShimpz/shimpz-frontend/tar.gz/f3bd0a0b9a8996ba085898b00c9c61ddd13b6d19': true

overrides:
  cookie: 0.7.2
  nanoid: 3.3.18
  postcss: 8.5.23
