<svelte:head>
  <title>Add an OAuth provider — Shimpz docs</title>
  <link rel="canonical" href="https://docs.shimpz.com/developers/assistants/spec/accounts/providers/" />
  <meta
    name="description"
    content="Add a Shimpz OAuth provider without exposing client credentials or creating provider-specific exceptions."
  />
</svelte:head>

<nav class="docs-breadcrumb" aria-label="Breadcrumb">
  <a href="/developers/">Developers</a><span aria-hidden="true">/</span><strong>Add an OAuth provider</strong>
</nav>

<header class="docs-page-header">
  <span class="section-label">Platform guide · OAuth 2.0</span>
  <h1>Reuse the flow, isolate the differences</h1>
  <p class="docs-lede">
    Every provider uses the same custody and Team isolation model. A small trusted adapter describes the
    provider differences; its Assistant declares only user-facing Powers, scopes, and API hosts.
  </p>
</header>

<aside class="scope-note" aria-labelledby="provider-status-title">
  <span id="provider-status-title" class="kicker">Important current limitation</span>
  <p>
    Cloudflare is the only registered provider today. The provider model is closed and fail-closed, but some
    broker paths and callback routes are still Cloudflare-specific. Provider two therefore requires a reviewed
    platform change as well as a new Assistant; changing only a manifest must fail.
  </p>
</aside>

<section class="guide-section" aria-labelledby="two-parts-title">
  <span class="section-label">Two coordinated parts</span>
  <h2 id="two-parts-title">Know which repository owns each decision</h2>
  <ol>
    <li>
      <strong>Trusted Shimpz platform:</strong> fixed OAuth endpoints, client authentication method, exact callbacks,
      allowed scopes, token parsing, refresh, revocation, broker routes, encrypted custody, and public provider name.
    </li>
    <li>
      <strong>Provider Assistant:</strong> exact API hosts, least-privilege Account scopes, useful Powers, closed
      schemas, bounded API transport, Help, Genesis, and provider-response redaction.
    </li>
  </ol>
</section>

<section class="guide-section" aria-labelledby="credentials-title">
  <span class="section-label">Credential ownership</span>
  <h2 id="credentials-title">Three credentials, three custodians</h2>
  <ul>
    <li><strong>OAuth client secret:</strong> encrypted in the private Neuron vault; never shipped to users.</li>
    <li><strong>Refresh token:</strong> encrypted and controller-owned for one Team, Assistant, Account, and scope set.</li>
    <li><strong>Access token:</strong> delivered only inside the selected Power's private invocation envelope.</li>
  </ul>
  <p>The browser, Brain, chat history, Store, Assistant manifest, and logs receive none of these values.</p>
</section>

<section class="guide-section" aria-labelledby="implementation-title">
  <span class="section-label">Implementation order</span>
  <h2 id="implementation-title">Add one read-only outcome end to end</h2>
  <ol>
    <li>Read the provider's current official OAuth and API documentation.</li>
    <li>Choose one useful read-only Power and determine its minimum scopes.</li>
    <li>Register the OAuth client and exact callback URLs generated by the implementation.</li>
    <li>Add one immutable provider definition; never accept endpoints from an Assistant or browser.</li>
    <li>Generalize broker and callback routing through the provider ID without keeping a Cloudflare compatibility branch.</li>
    <li>Store client credentials through Neuron's write-only encrypted form.</li>
    <li>Implement the Assistant Power with fixed paths, no redirects, strict timeouts, and response-size bounds.</li>
    <li>Complete real consent and prove the Power in stable before adding another Power.</li>
  </ol>
</section>

<section class="guide-section" aria-labelledby="scope-title">
  <span class="section-label">Scope changes</span>
  <h2 id="scope-title">A broader Power requires consent again</h2>
  <p>
    Shimpz binds a connected Account to its exact scope set. If a later Power needs more access, pause the turn
    and ask the person to authorize the new complete scope set. Do not assume a new token inherits scopes from
    an older grant, and do not merge tokens from separate grants.
  </p>
</section>

<section class="guide-section" aria-labelledby="evidence-title">
  <span class="section-label">Stable gate</span>
  <h2 id="evidence-title">Evidence required for every provider</h2>
  <ul>
    <li>State replay, expiry, provider mix-up, wrong callback, wrong Team, wrong Assistant, and wrong Account fail.</li>
    <li>Token responses reject redirects, duplicate fields, invalid content types, oversized bodies, and scope escalation.</li>
    <li>Refresh, disconnect, client-secret rotation, tampering, restart, and paused-turn continuation are tested.</li>
    <li>Logs, browser storage, chat, Power output, and exceptions are scanned for client secrets and tokens.</li>
    <li>The final stable image is immutable, digest-pinned, multi-platform, and validated by GitHub Actions.</li>
  </ul>
</section>

<nav class="docs-page-nav docs-page-nav-split" aria-label="Continue the developer guide">
  <a href="/developers/assistants/spec/"><span>Back</span><strong>Current contract</strong></a>
  <a href="/developers/assistants/spec/build-release/"><span>Next</span><strong>Validate and release</strong></a>
</nav>
